### ISSUE TITLE
incompatible JSON formats?

### ISSUE THREAD

**Issue by kcivey** [transistorsoft/background-geolocation-console#1]
Using a new install of the [sample app from Play](https://play.google.com/store/apps/details?id=com.transistorsoft.background_geolocation.ionic), we're getting errors related to the JSON format:

```
POST /locations {"location":{"activity":{"type":"still","confidence":100},"is_moving":false,"coords":{"latitude":38.9133995,"longitude":-77.0447084,"accuracy":30,"speed":0,"heading":0,"altitude":0},"timestamp":"2015-09-21T17:56:04Z"},"device_id":"18a91e39835f1398"}

TypeError: Cannot read property 'uuid' of undefined
    at Object.Location.create (/data/www/background-geolocation-console/server.js:116:41)
    at app.listen.host (/data/www/background-geolocation-console/server.js:39:12)
    at Layer.handle [as handle_request] (/data/www/background-geolocation-console/node_modules/express/lib/router/layer.js:95:5)
    at next (/data/www/background-geolocation-console/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/data/www/background-geolocation-console/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/data/www/background-geolocation-console/node_modules/express/lib/router/layer.js:95:5)
    at /data/www/background-geolocation-console/node_modules/express/lib/router/index.js:277:22
    at Function.process_params (/data/www/background-geolocation-console/node_modules/express/lib/router/index.js:330:12)
    at next (/data/www/background-geolocation-console/node_modules/express/lib/router/index.js:271:10)
    at /data/www/background-geolocation-console/node_modules/body-parser/lib/read.js:121:5
```

So the app is sending

```json
{
  "location": {
    "activity": {
      "type": "still",
      "confidence": 100
    },
    "is_moving": false,
    "coords": {
      "latitude": 38.9133995,
      "longitude": -77.0447084,
      "accuracy": 30,
      "speed": 0,
      "heading": 0,
      "altitude": 0
    },
    "timestamp": "2015-09-21T17:56:04Z"
  },
  "device_id": "18a91e39835f1398"
}
```

But server.js expects to have a `device` property that's an object with `uuid` and `model`. It's also expecting a `uuid` in the `location`. Is there a different app we should be using?

**Comment by christocracy** [comment]
Right, the console app is assuming #uuid exists.  it was added to plugin
recently.

The app in Play isn’t sending that.  I need to push an update.

Why don’t you build Android Sample App yourself?

On Mon, Sep 21, 2015 at 2:10 PM, Keith C. Ivey <notifications@github.com>
wrote:

> Using a new install of the sample app from Play
> <https://play.google.com/store/apps/details?id=com.transistorsoft.background_geolocation.ionic>,
> we're getting errors related to the JSON format:
>
> POST /locations {"location":{"activity":{"type":"still","confidence":100},"is_moving":false,"coords":{"latitude":38.9133995,"longitude":-77.0447084,"accuracy":30,"speed":0,"heading":0,"altitude":0},"timestamp":"2015-09-21T17:56:04Z"},"device_id":"18a91e39835f1398"}
>
> TypeError: Cannot read property 'uuid' of undefined
>     at Object.Location.create (/data/www/background-geolocation-console/server.js:116:41)
>     at app.listen.host (/data/www/background-geolocation-console/server.js:39:12)
>     at Layer.handle [as handle_request] (/data/www/background-geolocation-console/node_modules/express/lib/router/layer.js:95:5)
>     at next (/data/www/background-geolocation-console/node_modules/express/lib/router/route.js:131:13)
>     at Route.dispatch (/data/www/background-geolocation-console/node_modules/express/lib/router/route.js:112:3)
>     at Layer.handle [as handle_request] (/data/www/background-geolocation-console/node_modules/express/lib/router/layer.js:95:5)
>     at /data/www/background-geolocation-console/node_modules/express/lib/router/index.js:277:22
>     at Function.process_params (/data/www/background-geolocation-console/node_modules/express/lib/router/index.js:330:12)
>     at next (/data/www/background-geolocation-console/node_modules/express/lib/router/index.js:271:10)
>     at /data/www/background-geolocation-console/node_modules/body-parser/lib/read.js:121:5
>
> So the app is sending
>
> {
>   "location": {
>     "activity": {
>       "type": "still",
>       "confidence": 100
>     },
>     "is_moving": false,
>     "coords": {
>       "latitude": 38.9133995,
>       "longitude": -77.0447084,
>       "accuracy": 30,
>       "speed": 0,
>       "heading": 0,
>       "altitude": 0
>     },
>     "timestamp": "2015-09-21T17:56:04Z"
>   },
>   "device_id": "18a91e39835f1398"
> }
>
> But server.js expects to have a device property that's an object with uuid
> and model. It's also expecting a uuid in the location. Is there a
> different app we should be using?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/background-geolocation-console/issues/1>
> .
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>

**Comment by tacman** [comment]
I have difficulty getting the sample app to work.  Can you push an update to the app store?  That way we can test some things without the possibility that we've done something wrong in our code.

In the sample app, is there a way to force the app to send a location, so we can test this issue mentioned here without needing to walk around?

**Comment by christocracy** [comment]
Let's go on Skype today so I can find out why you have difficulty with
SampleApp.

On Tuesday, September 22, 2015, tacman <notifications@github.com> wrote:

> I have difficulty getting the sample app to work. Can you push an update
> to the app store? That way we can test some things without the possibility
> that we've done something wrong in our code.
>
> In the sample app, is there a way to force the app to send a location, so
> we can test this issue mentioned here without needing to walk around?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/background-geolocation-console/issues/1#issuecomment-142256955>
> .
>


-- 
Snet form Gmail Mobile

**Comment by christocracy** [comment]
Did you receive license last night?

On Tue, Sep 22, 2015 at 8:12 AM, Chris Scott <christocracy@gmail.com> wrote:

> Let's go on Skype today so I can find out why you have difficulty with
> SampleApp.
>
> On Tuesday, September 22, 2015, tacman <notifications@github.com> wrote:
>
>> I have difficulty getting the sample app to work. Can you push an update
>> to the app store? That way we can test some things without the possibility
>> that we've done something wrong in our code.
>>
>> In the sample app, is there a way to force the app to send a location, so
>> we can test this issue mentioned here without needing to walk around?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/transistorsoft/background-geolocation-console/issues/1#issuecomment-142256955>
>> .
>>
>
>
> --
> Snet form Gmail Mobile
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>

**Comment by tacman** [comment]
yep, everything working now.  The license and now I'm using 0.60, and the node app, integrating with our flagship app now.  Thanks.

**Comment by christocracy** [comment]
Awesome.  You're the first to confirm the new licensing feature works.

Were you not seeing a notification "TSLocationManager: invalid license"?

On Tuesday, September 22, 2015, tacman <notifications@github.com> wrote:

> yep, everything working now. The license and now I'm using 0.60, and the
> node app, integrating with our flagship app now. Thanks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/background-geolocation-console/issues/1#issuecomment-142323697>
> .
>


-- 
Snet form Gmail Mobile

**Comment by tacman** [comment]
No, but it may have been because my fork was out of sync.

**Comment by tacman** [comment]
OK, it's not actually working now.  If we post to the node server, it seems to be working, can you confirm that the POSTed data is defined at https://github.com/transistorsoft/cordova-background-geolocation/wiki/Location-Data-Schema

**Comment by kcivey** [comment]
The `uuid` in `location` is there and matches the schema, but the console server.js expects there to be a `device` as well as a `location`.

**Comment by christocracy** [comment]
Talk to @tacman.  It's up to you to add #device info to the #params if you wish.  I'm not going to re-invent the `cordova-plugin-device` functionality in this plugin.

You can see how SampleApp does it [here](https://github.com/transistorsoft/cordova-background-geolocation-SampleApp/blob/master/www/js/services.js#L273)
