### ISSUE TITLE
Nothing happens on server side (no map, no locations)

### ISSUE THREAD

**Issue by quanticware** [transistorsoft/background-geolocation-console#10]
Hi Chris, 

I have a little problem. 
I can synchronize the locations from my smartphone, it seems to be updated on server side.
But when I go to the web console, there is nothing. The device dropdown menu is empty, the filter button do nothing... Nothing happens

I have updated the repository (git pull), update npm modules (npm update).
Do you have any ideas what is going wrong with my server side background-geolocation-console ?

```
# node server.js 
*************************************************************************
* Background Geolocation Server listening at http://0.0.0.0:8080
************************************************************************* 

---------------------------------------------------------------------
- POST /locations
 {
  "location": {
    "coords": {
      "speed": -1,
      "longitude": 4.40230770871164,
      "latitude": 45.42891857995054,
      "accuracy": 65,
      "heading": -1,
      "altitude": 571.7623901367188,
      "altitudeAccuracy": 11.88654866067102
    },
    "is_heartbeat": true,
    "is_moving": false,
    "event": "motionchange",
    "uuid": "xxxxxxxx",
    "activity": {
      "type": "still",
      "confidence": 100
    },
    "battery": {
      "level": -1,
      "is_charging": 0
    },
    "timestamp": "2016-04-04T21:52:05.350Z"
  },
  "device": {
    "serial": "unknown",
    "manufacturer": "Apple",
    "available": true,
    "platform": "iOS",
    "cordova": "4.0.1",
    "uuid": "xxxxxx",
    "model": "iPhone7,2",
    "version": "9.3",
    "isVirtual": false
  }
} 
```

**Comment by quanticware** [comment]
I installed the repo on my mac, synced the locations...same issue...

**Comment by christocracy** [comment]
Any errors reported in browser's developer console?

**Comment by quanticware** [comment]
Info :
```
Navigated to http://localhost:8080/
ReactDOM.js:67 Download the React DevTools for a better development experience: https://fb.me/react-devtools
ReactDOM.js:67 Download the React DevTools for a better development experience: https://fb.me/react-devtools
```
Error :
```
invariant.js:40 Uncaught Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded (details: https://fb.me/react-refs-must-have-owner).invariant @ invariant.js:40ReactOwner.addComponentAsRefTo @ ReactOwner.js:68attachRef @ ReactRef.js:23ReactRef.attachRefs @ ReactRef.js:42attachRefs @ ReactReconciler.js:21assign.notifyAll @ CallbackQueue.js:66ON_DOM_READY_QUEUEING.close @ ReactReconcileTransaction.js:81Mixin.closeAll @ Transaction.js:203Mixin.perform @ Transaction.js:150batchedMountComponentIntoNode @ ReactMount.js:283Mixin.perform @ Transaction.js:137ReactDefaultBatchingStrategy.batchedUpdates @ ReactDefaultBatchingStrategy.js:62batchedUpdates @ ReactUpdates.js:95ReactMount._renderNewRootComponent @ ReactMount.js:477wrapper @ ReactPerf.js:67ReactMount._renderSubtreeIntoContainer @ ReactMount.js:551ReactMount.render @ ReactMount.js:571wrapper @ ReactPerf.js:672../actions/Actions @ app.js:46s @ _prelude.js:1e @ _prelude.js:1(anonymous function) @ _prelude.js:1
```
Warning :
```
util.js:220 Google Maps API warning: NoApiKeys https://developers.google.com/maps/documentation/javascript/error-messages#no-api-keys
util.js:220 Google Maps API warning: SensorNotRequired https://developers.google.com/maps/documentation/javascript/error-messages#sensor-not-required
```

**Comment by christocracy** [comment]
Are you keeping this running:
```
$ npm start
```

While running the server as well?
```
$ node server.js
```

I just cloned the repo from scratch and it works fine here.

```
$ node -v
v4.2.2

$ npm -v
2.14.7
ford:transistorsoft.com chris$
```

**Comment by quanticware** [comment]
No, npm is not running. Only "node server.js" is running.

This is on my online server
```
$ node -v
v0.10.43
$ npm -v
3.8.5
```

And this is on my mac
```
$ node -v
v0.12.4
$ npm -v
2.10.1
```

There is no node & npm requirement in the package.json of your project. Do I have to upgrade node and npm ?

**Comment by christocracy** [comment]
You need to run

$ npm start

Upgrade your node and npm.

On Thu, Apr 7, 2016 at 3:45 PM, quanticware <notifications@github.com>
wrote:

> No, npm is not running. Only "node server.js" is running.
>
> This is on my online server
>
> $ node -v
> v0.10.43
> $ npm -v
> 3.8.5
>
> And this is on my mac
>
> $ node -v
> v0.12.4
> $ npm -v
> 2.10.1
>
> There is no node & npm requirement in the package.json of your project. Do
> I have to upgrade node and npm ?
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/background-geolocation-console/issues/10#issuecomment-207063092>
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>

**Comment by quanticware** [comment]
I upgraded node and npm
So I started the two commands. It's working on my server, but not on my mac...

This is on my online server
```
$ node -v
v5.10.1
$ npm -v
3.8.3
```

And this is on my mac
```
$ node -v
v4.2.4
$ npm -v
2.14.14
```

Thank you Chris

**Comment by christocracy** [comment]
I really don't know.  It's an open source project that I happen to use for
the development of background Geolocation.


On Thursday, April 7, 2016, quanticware <notifications@github.com> wrote:

> I upgraded node and npm
> So I started the two commands. It's working on my server, but not on my
> mac...
>
> This is on my online server
>
> $ node -v
> v5.10.1
> $ npm -v
> 3.8.3
>
> And this is on my mac
>
> $ node -v
> v4.2.4
> $ npm -v
> 2.14.14
>
> Thank you Chris
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/background-geolocation-console/issues/10#issuecomment-207085695>
>


-- 
Snet form Gmail Mobile

**Comment by quanticware** [comment]
That's fine Chris. You can close the ticket. You solved it anyway.
Maybe you could add the node and npm version as a dependencies...

Thx

**Comment by aleclofabbro** [comment]
I'm getting same error on client :  
`invariant.js:40 Uncaught Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded (details: https://fb.me/react-refs-must-have-owner).`   

server seems working well, the aapp synced data to it, i've seen data on log,  
but webapp doesn't work

**Comment by christocracy** [comment]
App has been completely refactored.
