### ISSUE TITLE
Error while running npm run server

### ISSUE THREAD

**Issue by marks5** [transistorsoft/background-geolocation-console#102]
I've tried to run as your guide steps
npm install
npm run server

And then this happened

```
> background-geolocation-console@3.0.1 server /home/marques18/background-geolocation-console
> node server.js
internal/modules/cjs/loader.js:796
    throw err;
    ^
Error: Cannot find module '/home/marques18/background-geolocation-console/server.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17)
    at Function.Module._load (internal/modules/cjs/loader.js:686:27)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! background-geolocation-console@3.0.1 server: `node server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the background-geolocation-console@3.0.1 server script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/marques18/.npm/_logs/2020-02-14T03_12_47_930Z-debug.log
```

So I tried npm run start
It seems to start the server but not the website bundle and etc.

So I ended trying npm run dev
And seems to load web and api through curl output but I think it would be better to run on production.

Oh theres something weird happening that the port is always delivered as tpc6 so I ran into little problems by using nginx as reverse proxy as well using Lets Encrypt certificate.

**Comment by christocracy** [comment]
@Sigura ?

**Comment by pdelprat** [comment]
Hello,

Most often, package.json is written for linux and not for windows. You can see that "script" property use linux shell syntax and not windows shell syntax. 

`
  "scripts": {
    "lint": "eslint src/ && flow",
    "build": "NODE_ENV=production webpack",
    "start": "better-npm-run start",
    "dev": "better-npm-run dev",
    "test": "jest",
    "server": "node server.js",
    "heroku-postbuild": "rm -rf build/ && webpack -p --progress && NPM_CONFIG_PRODUCTION=true npm prune --production",
    "migrate": "babel-node ./src/server/database/migrate.js"
  }
`

My advice is to use Ubuntu for windows and use npm, node.js, vscode, etc.. on this environment.

I'm pretty sure you use windows ...

Hope this help,
Pascal

**Comment by Sigura** [comment]
@marks5 I'm sorry about the delay, fix merged.

you can try `node ./bin/server.js` without `git pull`

**Comment by marks5** [comment]
It seems to be fixed :)

But there's some typos trying to open browser on ports 8080 even if its running on 9000 after npm run server. 

Anyway, thank you!

I will try run on prod next week!
