### ISSUE TITLE
Console shows "No devices" even though there's data in database

### ISSUE THREAD

**Issue by dupiesdupreez** [transistorsoft/background-geolocation-console#117]
Good day team

I'm using flutter Background geolocation and implemented that fine into my app. I've then used Heroku to setup my database and console

Now I can see data being written into my postgres database. Into tables Companies, Devices and Locations, but in my console, It shows there are now devices to select.

Would you be able to help me on the right track?

I've got it to show once, but not again after clearing the database.

Console : https://response24-geolocation-console.herokuapp.com/

![image](https://user-images.githubusercontent.com/6910085/87925263-4c1fd280-ca80-11ea-950d-42be53335b5c.png)

![image](https://user-images.githubusercontent.com/6910085/87925373-7a9dad80-ca80-11ea-9cb5-a03b772e169e.png)

![image](https://user-images.githubusercontent.com/6910085/87925404-86896f80-ca80-11ea-8551-c6188e4ca7ef.png)

**Comment by christocracy** [comment]
See `[Start date.  ][v]` selector.

![](https://dl.dropbox.com/s/is8phqi5a3d02cc/Screenshot%202020-07-20%2008.15.00.png?dl=1)

**Comment by dupiesdupreez** [comment]
I'm sorry, but I don't understand?

How are you getting devices?

![image](https://user-images.githubusercontent.com/6910085/88038096-0d545000-cb46-11ea-9524-067a1cb559cf.png)

**Comment by dupiesdupreez** [comment]
Any help?
