### ISSUE TITLE
npm install issue

### ISSUE THREAD

**Issue by jaylucas** [transistorsoft/background-geolocation-console#12]
npm WARN react-google-maps@4.9.1 requires a peer of react@^0.14.0 but none was installed.
npm WARN react-google-maps@4.9.1 requires a peer of react-dom@^0.14.0 but none was installed.
npm WARN react-prop-types-element-of-type@1.0.2 requires a peer of react@^0.14.0 but none was installed.
npm WARN react-prop-types-element-of-type@2.0.0 requires a peer of react@^0.14.6 but none was installed.

**Comment by christocracy** [comment]
```
ford:transistorsoft.com chris$ npm -v
2.14.7
ford:transistorsoft.com chris$ node -v
v4.2.2
```

**Comment by christocracy** [comment]
Does the server boot?

**Comment by jaylucas** [comment]
npm -v 
3.8.3
node -v
v5.10.1

**Comment by christocracy** [comment]
App has been completely refactored.
