### ISSUE TITLE
Flutter app doesn't connect to console

### ISSUE THREAD

**Issue by MatyasK** [transistorsoft/background-geolocation-console#128]
so I have the console running on my desktop, on localhost:9000 I have set my Flutter up according to the docs but it doesn't send any request to the console.

it feels like I missing step somewhere, but I can't find it. I start the tracking with button press  and calling bg.BackgroundGeolocation.start();.

![image](https://user-images.githubusercontent.com/15628788/173619032-29d7c355-1701-4f78-8d6a-2c960c4e9be8.png)

**Comment by christocracy** [comment]
Also see the plugin api docs for `Config.transistorAuthorizationToken`.  It allows you to configure custom host with optional 3rd param (ie: `http://192.168.1.125:9000`)
