### ISSUE TITLE
Device params from flutter

### ISSUE THREAD

**Issue by MatyasK** [transistorsoft/background-geolocation-console#129]
I setup everything, I can see my data comming to the console, however I can't select devices. And the api receives empty id which you can see in the screenshot.

![image](https://user-images.githubusercontent.com/15628788/173664053-fcabb125-93ef-4b46-b932-622e1533e6f3.png)

My flutter setup is according to docs.

![image](https://user-images.githubusercontent.com/15628788/173664277-3ae6da31-455d-478f-86ab-81685178d3b8.png)

**Comment by christocracy** [comment]
See my last comment on your other issue and use `Config.transistorAuthorizationToken`.

**delete your `url` and `params`.**  You do not need to manually provide `deviceParams`.

`TransistorAutorizationToken` **does everything required for successfully posting to `background-geolocation-console` app.**

**Comment by MatyasK** [comment]
I did setup TransistorAutorizationToken, and removed the url and params, but it still doesn't show up  in the console.

![image](https://user-images.githubusercontent.com/15628788/173671538-d6a32daf-1487-4357-b4b4-be24e547c8a4.png)

![image](https://user-images.githubusercontent.com/15628788/173671358-116543db-3cd5-4759-a44f-c8e4975a4e18.png)

**Comment by MatyasK** [comment]
I solved my issue, the url needs to be set without the / in the end, thanks for your help, we can give a proper test to it now!
