### ISSUE TITLE
do you revert the code to old version?

### ISSUE THREAD

**Issue by barart** [transistorsoft/background-geolocation-console#133]
I was using this on heroku from time ago (almost a year), now that heroku is going to end the free dynos i come here to grab the "latest" version, however when i run it i found that the menu looks like is not stylized (older) also i found that are missing some options like "max pins" and i find that the package.json has version 1.0.0 when it was on version": "3.0.1", (my old package file has that version)

What happened?

**Comment by christocracy** [comment]
The front end app was completely refactored last year and the current version number has no correlation to the past.

the version in master is the current version.
