### ISSUE TITLE
Feature request: minimum threshold for stopTimeout to get interrupted

### ISSUE THREAD

**Issue by sirusbaladi** [transistorsoft/background-geolocation-console#139]
Hi, sometimes the user is within the same location but does some movements.

Example
- user is at a bar and moves within 15 / 20 meters within the bar.

In cases like the above the stopTimeout keeps getting interrupted and the app never reaches stationary state while it should. 

Any way to set a minimum threshold of movement for timer to interrupted? if no, could we have this in a future version?

Thanks.

**Comment by christocracy** [comment]
I do something on the opposite end of things with Config.motionTriggerDelay, delaying the transition to the *moving* state while, for example, walking around the house.

I’ll think about this.

**Comment by christocracy** [comment]
This is the wrong place to post this issue.  This is the repo for the demo server.

**Comment by sirusbaladi** [comment]
> I do something on the opposite end of things with Config.motionTriggerDelay, delaying the transition to the _moving_ state while, for example, walking around the house.
> 
> I’ll think about this.

Great thanks.
One of my testers was trying new shoes at a shoe store for over an hour. The shop is not big but they kept walking back on forth to test different shoes. The moving state kept staying active because of that.

**Comment by sirusbaladi** [comment]
> This is the wrong place to post this issue. This is the repo for the demo server.

oh just noticed. should I close and repost on the right repo?

**Comment by christocracy** [comment]
> oh just noticed. should I close and repost on the right repo?

Yes.  I manage 8 different repos for the plug-in for Cordova, Capacitor, React Native and Flutter.

**Comment by sirusbaladi** [comment]
closing
