### ISSUE TITLE
Why the BackgroundGeolocation stop getting coordinates when the app is terminated (ANDROID)

### ISSUE THREAD

**Issue by SMuncal** [transistorsoft/background-geolocation-console#143]
Hi Team,

I have question regarding BackgroundGeolocation, we experience bugs on android platform when
the app is terminated or minimize the we can't receive any location, however the IOS is working fine.

Here is the sample code:

![Uploading carbon (7).png…]()

**Comment by christocracy** [comment]
This is the repo for the demo server.  This is not the place to seek support for the Background Geolocation plugin.

Seek support by posting an issue at the proper github repo for the version of the plugin you're using (ie: *React Native*, *Capacitor*, *Cordova*, *Flutter*).
