### ISSUE TITLE
error while running/building

### ISSUE THREAD

**Issue by nikhilpal** [transistorsoft/background-geolocation-console#19]
ubuntu@ip-172-31-23-184:background-geolocation-console$ npm --version
2.14.7
ubuntu@ip-172-31-23-184:background-geolocation-console$ node --version
v4.2.2

ubuntu@ip-172-31-23-184:~/background-geolocation-console$ npm run build

> background-geolocation-console@0.1.0 build /home/ubuntu/background-geolocation-console
> browserify . -o js/bundle.js -t [ babelify --presets [ es2015 react ] ]

Error: Cannot find module 'react-dom/lib/ReactDOM' from '/home/ubuntu/background-geolocation-console/node_modules/material-ui/node_modules/react/lib'
    at /home/ubuntu/background-geolocation-console/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:46:17
    at process (/home/ubuntu/background-geolocation-console/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:173:43)
    at ondir (/home/ubuntu/background-geolocation-console/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:188:17)
    at load (/home/ubuntu/background-geolocation-console/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/home/ubuntu/background-geolocation-console/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /home/ubuntu/background-geolocation-console/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:82:15)

npm ERR! Linux 3.2.0-40-virtual
npm ERR! argv "/home/ubuntu/.nvm/versions/node/v4.2.2/bin/node" "/home/ubuntu/.nvm/versions/node/v4.2.2/bin/npm" "run" "build"
npm ERR! node v4.2.2
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE
npm ERR! background-geolocation-console@0.1.0 build: `browserify . -o js/bundle.js -t [ babelify --presets [ es2015 react ] ] `
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the background-geolocation-console@0.1.0 build script 'browserify . -o js/bundle.js -t [ babelify --presets [ es2015 react ] ] '.
npm ERR! This is most likely a problem with the background-geolocation-console package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     browserify . -o js/bundle.js -t [ babelify --presets [ es2015 react ] ]
npm ERR! You can get their info via:
npm ERR!     npm owner ls background-geolocation-console
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/background-geolocation-console/npm-debug.log

**Comment by christocracy** [comment]
Upgrade Node / npm.

**Comment by nikhilpal** [comment]
@christocracy what is the recommended version? I can upgrade and try

**Comment by christocracy** [comment]
See [Install node](https://nodejs.org/en/download/)

**Comment by jorgemejia** [comment]
@nikhilpal Did you solve this issue?

**Comment by christocracy** [comment]
Actually, I'm about to post a completely refactored version of this app using latest React and Webpack.

**Comment by christocracy** [comment]
Ok, new version is up.  See the [README](https://github.com/transistorsoft/background-geolocation-console#running) for new setup steps.

This is a **completely** new app.  You should start by re-cloning the repo.
