### ISSUE TITLE
npm install not working.

### ISSUE THREAD

**Issue by muphy** [transistorsoft/background-geolocation-console#2]
run command:
  ``` npm install ``` 

output:
  ```
root@test:~/server/background-geolocation-console# npm install
npm WARN package.json background-geolocation-console@0.0.3 No license field.
npm WARN unmet dependency /root/server/background-geolocation-console/node_modules/react-chartist requires react@'^0.13.2' but will load
npm WARN unmet dependency /root/server/background-geolocation-console/node_modules/react,
npm WARN unmet dependency which is version 0.13.0
npm ERR! Linux 3.13.0-52-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/local/bin/npm" "install"
npm ERR! node v4.2.2
npm ERR! npm  v2.11.1
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package react does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer fixed-data-table@0.4.7 wants react@>=0.13.0 <0.15.0 || ^0.14.0-beta3
npm ERR! peerinvalid Peer google-map-react@0.4.2 wants react@>=0.13.0 <0.15.0 || ^0.14.0-beta1
npm ERR! peerinvalid Peer material-ui@0.11.1 wants react@>=0.13
npm ERR! peerinvalid Peer react-chartist@0.8.0 wants react@>=0.13.0
npm ERR! peerinvalid Peer react-chartjs@0.6.0 wants react@*
npm ERR! peerinvalid Peer react-datagrid@1.2.15 wants react@>=0.13.0
npm ERR! peerinvalid Peer react-flexbox@2.0.2 wants react@0.13.x
npm ERR! peerinvalid Peer react-google-maps@2.2.0 wants react@^0.13.0
npm ERR! peerinvalid Peer react-googlemaps@0.4.0 wants react@>=0.12.1
npm ERR! peerinvalid Peer react-router@0.13.5 wants react@0.13.x||0.14.x
npm ERR! peerinvalid Peer react-tap-event-plugin@0.1.8 wants react@^0.14.0-0 || ~0.13.x || ~0.12.x
npm ERR! peerinvalid Peer react-dom@0.14.2 wants react@^0.14.2
```

**Comment by muphy** [comment]
I have modified your package.json which was working.

```
{
	"name": "background-geolocation-console",
	"version": "0.0.3",
	"description": "A field-testing/analysis server & web-app for the Background Geolocation plugin",
	"repository": "https://github.com/transistorsoft/background-geolocation-console",
	"main": "js/app.js",
	"dependencies": {
		"body-parser": "^1.13.3",
		"chart.js": "^1.0.2",
		"chartist": "^0.9.4",
		"classnames": "^2.1.3",
		"express": "^4.13.3",
		"fixed-data-table": "0.5.0",
		"flux": "^2.1.1",
		"fluxxor": "^1.7.1",
		"google-map-react": "^0.4.1",
		"keymirror": "~0.1.0",
		"material-ui": "^0.11.0",
		"moment": "^2.10.6",
		"object-assign": "^1.0.0",
		"react": "0.4.2",
		"react-chartist": "0.10.1",
		"react-chartjs": "0.6.0",
		"react-datagrid": "1.2.15",
		"react-flexbox": "3.0.0",
		"react-google-maps": "4.2.0",
		"react-googlemaps": "0.4.0",
		"react-router": "1.0.0-rc4",
		"react-tap-event-plugin": "^0.1.7",
		"sqlite3": "3.1.1"
	},
	"devDependencies": {
		"babelify": "^6.3.0",
		"browserify": "^6.2.0",
		"envify": "^3.0.0",
		"jest-cli": "^0.4.3",
		"reactify": "^0.17.1",
		"uglify-js": "~2.4.15",
		"watchify": "^2.1.1"
	},
	"scripts": {
		"start": "watchify -o js/bundle.js -v -d js/app.js",
		"build": "browserify . -t [envify --NODE_ENV production] | uglifyjs -cm > js/bundle.min.js",
		"test": "jest"
	},
	"author": "Chris Scott, Transistor Software",
	"browserify": {
		"transform": [
			"reactify",
			"babelify",
			"envify"
		]
	},
	"jest": {
		"rootDir": "./js"
	}
}

```

**Comment by christocracy** [comment]
Would you like to send that as a push-request?

On Thu, Nov 5, 2015 at 11:40 AM, JongAm Oh <notifications@github.com> wrote:

> I have modified your package.json which was working.
>
> {
>     "name": "background-geolocation-console",
>     "version": "0.0.3",
>     "description": "A field-testing/analysis server & web-app for the Background Geolocation plugin",
>     "repository": "https://github.com/transistorsoft/background-geolocation-console",
>     "main": "js/app.js",
>     "dependencies": {
>         "body-parser": "^1.13.3",
>         "chart.js": "^1.0.2",
>         "chartist": "^0.9.4",
>         "classnames": "^2.1.3",
>         "express": "^4.13.3",
>         "fixed-data-table": "0.5.0",
>         "flux": "^2.1.1",
>         "fluxxor": "^1.7.1",
>         "google-map-react": "^0.4.1",
>         "keymirror": "~0.1.0",
>         "material-ui": "^0.11.0",
>         "moment": "^2.10.6",
>         "object-assign": "^1.0.0",
>         "react": "0.4.2",
>         "react-chartist": "0.10.1",
>         "react-chartjs": "0.6.0",
>         "react-datagrid": "1.2.15",
>         "react-flexbox": "3.0.0",
>         "react-google-maps": "4.2.0",
>         "react-googlemaps": "0.4.0",
>         "react-router": "1.0.0-rc4",
>         "react-tap-event-plugin": "^0.1.7",
>         "sqlite3": "3.1.1"
>     },
>     "devDependencies": {
>         "babelify": "^6.3.0",
>         "browserify": "^6.2.0",
>         "envify": "^3.0.0",
>         "jest-cli": "^0.4.3",
>         "reactify": "^0.17.1",
>         "uglify-js": "~2.4.15",
>         "watchify": "^2.1.1"
>     },
>     "scripts": {
>         "start": "watchify -o js/bundle.js -v -d js/app.js",
>         "build": "browserify . -t [envify --NODE_ENV production] | uglifyjs -cm > js/bundle.min.js",
>         "test": "jest"
>     },
>     "author": "Chris Scott, Transistor Software",
>     "browserify": {
>         "transform": [
>             "reactify",
>             "babelify",
>             "envify"
>         ]
>     },
>     "jest": {
>         "rootDir": "./js"
>     }
> }
>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/background-geolocation-console/issues/2#issuecomment-154116258>
> .
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>

**Comment by muphy** [comment]
Yes I will.
> 2015. 11. 6., 오전 1:41, Chris Scott <notifications@github.com> 작성:
> 
> Would you like to send that as a push-request?
>

**Comment by YoungElPaso** [comment]
Was it ever pushed?

**Comment by YoungElPaso** [comment]
Ah, I see the history.

**Comment by YoungElPaso** [comment]
Guess I'll add to it.  Unless I bump react to 0.14.3 I get similar errors, around react-dom as well.

**Comment by phamminhvu** [comment]
I got an issue When I try to run command:
Node server.js
TypeError: Cannot read property 'forEach' of undefined
    at onQuery (server.js:79:13)
    at Statement.errBack (node_modules/sqlite3/lib/sqlite3.js:16:21)
--> in Database#all('SELECT device_id, device_model FROM locations GROUP BY device_id, device_model ORDER BY recorded_at DESC', [Function])
    at Object.Device.all (server.js:84:11)
    at server.js:20:10
