### ISSUE TITLE
Overall UI ideas

### ISSUE THREAD

**Issue by ZeusTheTrueGod** [transistorsoft/background-geolocation-console#25]
- Watch mode for a 'DATA' tab limits the amount of rows to just one, but that is not obvious to a user that only the latest row is displayed. I would just add a 'only a latest row is displayed in a watch mode' label to make it clear.

- Lat/Lng displays too much digits, obviously just 6 would be enough.

- The app is not backed by redux, thus switching watch mode on/off does not affect data immediately, you have to refresh the grid in order to get all the records after turning off the watch mode

- Time control is not easy to use, need some time to get used to the way how the hour/minute is chosen

- It seems like there is no auto refresh every minute or so. 

- Grid and map were empty after a first sync , in order to get some data I had to manually choose the device from the filter. It would be nice if a device is selected automatically, and if there is only one device, no need to display it as a select at all

- choosing a row is not that obvious, would be nice if just clicking on a row would make it selected, because there is already a 'hover' style

- when you choose a marker on the map, and then switch to the grid, then that marker is marked as selected, which is good, but the grid is not scrolled to that position, which is not that good. Would be nice to scroll to that marker.

- horizontal and vertical scroll should belong just to the grid rows area, not to the grid headers and logo. This way it is easy to switch between a map and a grid, plus the logo 'Transistor Software' does not go away on either horizontal or vertical scroll

**Comment by christocracy** [comment]
Ok, go ahead and get started.

**Comment by ZeusTheTrueGod** [comment]
Done
