### ISSUE TITLE
POST /locations can handle a batch-request

### ISSUE THREAD

**Issue by christocracy** [transistorsoft/background-geolocation-console#28]
The plugin has a config `batchSync` which allows the plugin to post multiple locations in a single request.

The `/locations` route needs to sense that `req.body` is `[{}, {}, ...]` or `{}`.

When it's `[]`, iterate and execute `#createLocation`

**Comment by christocracy** [comment]
@ZeusTheTrueGod

**Comment by ZeusTheTrueGod** [comment]
There was a support for that already in 
```
const locations = location.length ? location : [location];
```
Anyway, I added a support if the whole req.body is an array too.

**Comment by ZeusTheTrueGod** [comment]
I've pushed my changes to heroku
