### ISSUE TITLE
Implement Google Analytics

### ISSUE THREAD

**Issue by christocracy** [transistorsoft/background-geolocation-console#29]
@ZeusTheTrueGod I've added a new Heroku config `GOOGLE_ANALYTICS_ID`.

It seems that `index.html` will have to be turned into an `ejs` template and rendered on the server rather than being served statically now.  In the document `<head>`:

```html
<head>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
 
  ga('create', '<%= process.env.GOOGLE_ANALYTICS_ID %>', 'auto');
  ga('send', 'pageview');
 
</script>
</head>
```

**Comment by ZeusTheTrueGod** [comment]
Done, pushed to heroku.

**Comment by christocracy** [comment]
Open up another PR.  Last one one was closed

**Comment by ZeusTheTrueGod** [comment]
https://github.com/transistorsoft/background-geolocation-console/pull/30/files
@christocracy
