### ISSUE TITLE
Module not found: event-emitter

### ISSUE THREAD

**Issue by markacianfrani** [transistorsoft/background-geolocation-console#38]
Node version: 8.7.0

Getting this error trying to npm run server:

`ERROR in ./src/client/globalBus.js
Module not found: Error: Can't resolve 'event-emitter' in '/Users/mark/Desktop/background-geolocation-console/src/client'
 @ ./src/client/globalBus.js 1:0-36
 @ ./src/client/components/ListView.js
 @ ./src/client/components/Viewport.js
 @ ./src/client/main.js
 @ multi webpack-hot-middleware/client?path=/__webpack_hmr&timeout=20000 react-hot-loader/patch ./main.js`

**Comment by davidroman0O** [comment]
Same error for me! @christocracy any idea ? :)

**Comment by christocracy** [comment]
Confirmed and fixed in master.

**Comment by davidroman0O** [comment]
Thx a lot @christocracy
