### ISSUE TITLE
Is device info required to show data?

### ISSUE THREAD

**Issue by markacianfrani** [transistorsoft/background-geolocation-console#41]
I'm not sure if this questions belongs here or over at cordova-background-geolocation-lt but I was initially have some issues with my data not showing up in the UI. It was POSTing fine and the background-geolocation.db had everything in there, it just wasnt populating on the screen.

I pulled the sample app and saw that was working and eventually traced it down to my POST request from my app wasn't including the device object. Once I added that, everything started showing up. Without it, the device just showed up as UNKNOWN. 

I'm manually adding the device info in my app as a param in the initial config. It wasn't doing that by default which is probably intended. 

I'm not sure if I just missed something but if not, it might be a good idea to mention this somewhere in the README (I could make a pull request) or possibly change the backend to accommodate not having any device info. I unfortunately dont know enough of React to be of any use with the later. 

Figured I would document my issue here in case anyone else from the future makes the same mistake.

**Comment by christocracy** [comment]
Yes, device info is required.  That’s how the app associates the data without added complexity of registration/login system.

This console server is primarily designed for use with the SampleApp, which is already configured to append device-data, but yes, I’ve been meaning to document this for use in one’s own app.

**Comment by phil-andrews** [comment]
What does the device info object look like? Is it this...

```  params: {               // <-- Optional HTTP params
    'fake-auth-token': 'fake-auth-token-hash',
    device: {
      uuid: (DeviceInfo.getModel() + '-' + DeviceInfo.getSystemVersion()).replace(/[\s\.,]/g, '-'),
      device_model: DeviceInfo.getModel(),
      platform: DeviceInfo.getSystemName(),
      manufacturer: DeviceInfo.getManufacturer(),
      version: DeviceInfo.getSystemVersion(),
      framework: 'ReactNative'
    }
  }```

**Comment by christocracy** [comment]
@phil-andrews For React Native, there's a new convenience method to compose the required param object [`transistorTrackerParams`](https://transistorsoft.github.io/react-native-background-geolocation/classes/_react_native_background_geolocation_.backgroundgeolocation.html#transistortrackerparams)
