### ISSUE TITLE
Issue on 'npm install'

### ISSUE THREAD

**Issue by VJR4J** [transistorsoft/background-geolocation-console#49]
npm WARN deprecated cryptiles@2.0.5: This version is no longer maintained. Please upgrade to the latest version.
npm WARN deprecated boom@2.10.1: This version is no longer maintained. Please upgrade to the latest version.
npm WARN deprecated hoek@2.16.3: This version is no longer maintained. Please upgrade to the latest version.

> sqlite3@3.1.13 install C:\Users\vinayak.surywanshi\react\background-geolocation-console\node_modules\sqlite3

> node-pre-gyp install --fallback-to-build
node-pre-gyp ERR! Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.13/node-v67-win32-x64.tar.gz

node-pre-gyp ERR! Pre-built binaries not found for sqlite3@3.1.13 and node@11.4.0 (node-v67 ABI) (falling back to source compile with node-gyp)

node-pre-gyp ERR! Tried to download(undefined): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.13/node-v67-win32-x64.tar.gz

node-pre-gyp ERR! Pre-built binaries not found for sqlite3@3.1.13 and node@11.4.0 (node-v67 ABI) (falling back to source compile with node-gyp)

Traceback (most recent call last):

  File "C:\Users\vinayak.surywanshi\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\gyp\gyp_main.py", line 16, in <module>
    sys.exit(gyp.script_main())
  File "C:\Users\vinayak.surywanshi\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 545, in script_main
    return main(sys.argv[1:])
  File "C:\Users\vinayak.surywanshi\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 538, in main
    return gyp_main(args)
  File "C:\Users\vinayak.surywanshi\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 523, in gyp_main
    generator.GenerateOutput(flat_list, targets, data, params)
  File "C:\Users\vinayak.surywanshi\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 2025, in GenerateOutput
    version=msvs_version)
  File "C:\Users\vinayak.surywanshi\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\MSVSNew.py", line 213, in __init__
    self.Write()
  File "C:\Users\vinayak.surywanshi\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\MSVSNew.py", line 340, in Write
    f.close()
  File "C:\Users\vinayak.surywanshi\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\common.py", line 393, in close
    os.rename(self.tmp_path, filename)
WindowsError: [Error 183] Cannot create a file when that file already exists
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\vinayak.surywanshi\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:345:16)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\vinayak.surywanshi\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=C:\\Users\\vinayak.surywanshi\\react\\background-geolocation-console\\node_modules\\sqlite3\\lib\\binding\\node-v67-win32-x64\\node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=C:\\Users\\vinayak.surywanshi\\react\\background-geolocation-console\\node_modules\\sqlite3\\lib\\binding\\node-v67-win32-x64" "--python=C:\\Users\\vinayak.surywanshi\\.windows-build-tools\\python27\\python.exe"
gyp ERR! cwd C:\Users\vinayak.surywanshi\react\background-geolocation-console\node_modules\sqlite3
gyp ERR! node -v v11.4.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\vinayak.surywanshi\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=C:\Users\vinayak.surywanshi\react\background-geolocation-console\node_modules\sqlite3\lib\binding\node-v67-win32-x64\node_sqlite3.node --module_name=node_sqlite3 --module_path=C:\Users\vinayak.surywanshi\react\background-geolocation-console\node_modules\sqlite3\lib\binding\node-v67-win32-x64 --python=C:\Users\vinayak.surywanshi\.windows-build-tools\python27\python.exe' (1)

node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\vinayak.surywanshi\react\background-geolocation-console\node_modules\sqlite3\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:978:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
node-pre-gyp ERR! System Windows_NT 10.0.17134
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\vinayak.surywanshi\\react\\background-geolocation-console\\node_modules\\sqlite3\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Users\vinayak.surywanshi\react\background-geolocation-console\node_modules\sqlite3
node-pre-gyp ERR! node -v v11.4.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.38
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\vinayak.surywanshi\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=C:\Users\vinayak.surywanshi\react\background-geolocation-console\node_modules\sqlite3\lib\binding\node-v67-win32-x64\node_sqlite3.node --module_name=node_sqlite3 --module_path=C:\Users\vinayak.surywanshi\react\background-geolocation-console\node_modules\sqlite3\lib\binding\node-v67-win32-x64 --python=C:\Users\vinayak.surywanshi\.windows-build-tools\python27\python.exe' (1)
npm WARN rollback Rolling back node-pre-gyp@0.6.38 failed (this is probably harmless): EPERM: operation not permitted, lstat 'C:\Users\vinayak.surywanshi\react\background-geolocation-console\node_modules\sqlite3\node_modules'
npm WARN rollback Rolling back readable-stream@2.3.3 failed (this is probably harmless): EPERM: operation not permitted, rmdir 'C:\Users\vinayak.surywanshi\react\background-geolocation-console\node_modules\sqlite3\node_modules'
npm WARN rollback Rolling back ajv@4.11.8 failed (this is probably harmless): EPERM: operation not permitted, rmdir 'C:\Users\vinayak.surywanshi\react\background-geolocation-console\node_modules\sqlite3\node_modules'
npm WARN rollback Rolling back tar-pack@3.4.0 failed (this is probably harmless): EPERM: operation not permitted, rmdir 'C:\Users\vinayak.surywanshi\react\background-geolocation-console\node_modules\sqlite3\node_modules'
npm WARN ajv-keywords@2.1.1 requires a peer of ajv@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN The package postcss-cssnext is included as both a dev and production dependency.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sqlite3@3.1.13 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sqlite3@3.1.13 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\vinayak.surywanshi\AppData\Roaming\npm-cache\_logs\2018-12-11T21_06_30_623Z-debug.log

**Comment by christocracy** [comment]
npm ERR! sqlite3@3.1.13 install: node-pre-gyp install --fallback-to-build
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sqlite3@3.1.13 install 

Google it.

**Comment by mikehardy** [comment]
If you update the sqlite3 dependency it appears to work fine - I just proposed a PR for this which may not be acceptable for the mainline code here, but might be useful for you #54

**Comment by mikehardy** [comment]
closable after merge of #54
