### ISSUE TITLE
Plaintext disallowed by default for Android targetAPI >= 28 / iOS >= 9

### ISSUE THREAD

**Issue by mikehardy** [transistorsoft/background-geolocation-console#55]
React-Native uses targetAPI 28 for RN0.59 and higher (and this already applies for people that have attempted it locally), so future example apps testing this are about to see that Android API28 disallows cleartext by default for transport, and I believe it is also disallowed for iOS >= 9

This results in mostly silent failure to post any locations to the server. (There are log messages, but they don't show up with app-specific filters - so developers might miss them)

To use the public version of the tracker or the default install of a local version the console must either have a valid certificate (via LetsEncrypt for instance) or the developer needs to implement a cleartext exception

An example workaround for developers in their apps is like so: https://github.com/facebook/react-native/pull/23429 for Android or like so https://stackoverflow.com/a/40299837 for iOS 

I'd be happy to propose a PR that modifies startup to optionally try using [the easiest LetsEncrypt module I've found for express and personally used](https://git.coolaj86.com/coolaj86/greenlock-express.js), or that just modifies the documentation pointing out the need for a cleartext exception and the official implementation of same

**Comment by mikehardy** [comment]
I've decided integrating LetsEncrypt via greenlock express is easy but terrible, probably best to just drop a hint in the docs that SSL is required unless you do an exception like is done for the react-native dev bundle server, and suggest using nginx + letsencrypt in front of the console. That seems to be the right separation of concerns (to me)

**Comment by Sigura** [comment]
Hello @mikehardy!

I have added `docker-compose` support in PR #111.  I can add `nginx` configuration with SSL support. Maybe with a self-sign certificate for as simple example.

**Comment by mikehardy** [comment]
Closing out old issues / personal git cleaning...
