### ISSUE TITLE
Regarding google billing

### ISSUE THREAD

**Issue by venturefarmer** [transistorsoft/background-geolocation-console#57]
we are currently using background geolocation console for testing purposes. PFA screenshot of google billing. 
**i would need explanation why google is charging me for Geocoding services.** 
![2019-03-28 (4)](https://user-images.githubusercontent.com/47856998/55149846-2b53a100-5108-11e9-841f-8b67f90181f0.png)

**Comment by christocracy** [comment]
I have no idea.

**Comment by christocracy** [comment]
this repo has nothing to do with *your* google api key.
