### ISSUE TITLE
deploy the application on a vps server

### ISSUE THREAD

**Issue by marking11** [transistorsoft/background-geolocation-console#61]
Hello,
I have a VPS server, can i deploy the application , or i need heroku ?

Many thanks,

**Comment by christocracy** [comment]
No, you don't need Heroku.

**Comment by marking11** [comment]
In the source code, where the locations are saved exactly ? Many thanks

**Comment by christocracy** [comment]
Obviously, you'd start in the [`/src`](https://github.com/transistorsoft/background-geolocation-console/tree/master/src) folder.
- `client`
- `server`

Obviously it's going to be in the `/server`.  Hmm...`/models` looks interesting.  Let's go in there:

Oooh...a [`Location`](https://github.com/transistorsoft/background-geolocation-console/tree/master/src/server/models) model, very interesting.

**Comment by marking11** [comment]
Good, but the problem here if we have multiple client and multiple taxi to track , each client is associated to one taxi, we need to have a reference between taxi and client ( one to one relation) this databse won't work,  how we can associate this to php/mysql database.

Many thanks.

**Comment by christocracy** [comment]
This is an open-source project designed for my own testing purposes and *certainly not* suitable for a production application.

I provide no support for this project.  If you want to use it, fork it and modify as desired.

**Comment by christocracy** [comment]
With `tracker.transistorsoft.com` running on Heroku, my database uses Postgres running on a completely different server at Digital Ocean.   See [DATABASE_URL](https://github.com/transistorsoft/background-geolocation-console/blob/master/src/server/database/define-sequelize-db.js#L11)

**Comment by marking11** [comment]
I understand, i deployed the project on local and run sample app when i check the database the table locations is empty there is no record.

**Comment by christocracy** [comment]
the url for localhost is `/locations` (not `/locations/username`)

**Comment by marking11** [comment]
Yes an empty array []

**Comment by marking11** [comment]
i use this configuration :
configureBackgroundGeolocation: function(username) {
        username = username || 'cordova-basic';

        var bgGeo = window.BackgroundGeolocation;
        app.bgGeo = bgGeo;

        ////
        // Step 1:  Listen to events.  It's always best to listen to events first, before #configure
        //

        // location event: Fires whenever a location is recorded.
        bgGeo.on('location', function(location) {
            console.log('[event] location: ', location);
            app.setLocation(location);
        }, function(error) {
            console.warn('[event] location error: ', error);
        });

        // motionchange event:  Fires when plugin changes state from Stationary->Moving and vice-versa.
        bgGeo.on('motionchange', function(isMoving, location) {
            console.log('[event] motionchange, isMoving: ', isMoving, ', location: ', location);
            app.setState({
                enabled: true,
                isMoving: isMoving
            });
        });

        // providerchange event:  Fires when user changes location authorization)
        bgGeo.on('providerchange', function(provider) {
            console.log('[event] providerchange: ', provider);
            app.setProvider(provider);
        });

        // heartbeat event:  Fires every heartbeatInterval while plugin is in stationary state.  iOS requires preventSuspend: true)
        bgGeo.on('heartbeat', function(event) {
            console.log('[event] heartbeat: ', event);
        });
    
        ////
        // Step 2:  Configure the plugin ONCE when your app boots.
        //

        bgGeo.configure({
            desiredAccuracy: 0,     // Highest possible accuracy: GPS + Wifi + Cellular
            distanceFilter: 10,     // Record a location every 10 meters.
            stopTimeout: 1,         // Change state to stationary after 1 min with device "still"
            stopOnTerminate: false, // Don't stop tracking when app is terminated.
            foregroundService: true,// Prevent Android from terminating service due to memory pressure from other apps.
            heartbeatInterval: 60,  // <-- heartbeat event every 60s
            url: 'https://' + app.host + '/locations',
            params: BackgroundGeolocation.transistorTrackerParams(window.device),
            //BackgroundGeolocation.transistorTrackerParams(window.device),
            //this.getParams(username),
            debug: true,            // Debug sounds & notifications
            autoSync: true,         // Auto sync each recorded location to #url immediately.
            logLevel: bgGeo.LOG_LEVEL_VERBOSE
        }, function(state) {
            app.setState(state);
            console.log('- BackgroundGeolocation is configured and ready to use');
        });

        // Wire-up UI
        var btnEnable = document.getElementById('btn-enable');
        var btnChangePace = document.getElementById('btn-changePace');
        var btnGetCurrentPosition = document.getElementById('btn-getCurrentPosition');
        var label = document.getElementById('label-view-tracker');

        btnEnable.addEventListener('click', this.onToggleEnabled.bind(this));
        btnChangePace.addEventListener('click', this.onClickChangePace.bind(this));
        btnGetCurrentPosition.addEventListener('click', this.onClickGetCurrentPosition.bind(this));

        // Write label message of where to view tracking history
        label.innerHTML = 'View your tracking at http://' + app.host + '/' + username;
    },

**Comment by christocracy** [comment]
```
$ cordova plugins
```

**Comment by marking11** [comment]
cordova-background-geolocation-lt 3.0.3 "BackgroundGeolocation"
cordova-plugin-background-fetch 5.4.1 "CDVBackgroundFetch"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-dialogs 2.0.2-dev "Notification"
cordova-plugin-whitelist 1.3.3 "Whitelist"

**Comment by christocracy** [comment]
- why are you using *deprecated* `#configure` method instead of new `#ready`?
- why are you using *deprecated* `#on` method instead of new `#onLocation`, `#onMotionChange`, etc?

**Comment by marking11** [comment]
i chnage the deprecated method, when debugging i have the exact locations but the location is not sent to the server .

onDeviceReady: function() {
        this.receivedEvent('deviceready');
        alert("ready");

        // 1.  Listen to events
  var bgGeo = window.BackgroundGeolocation;

  bgGeo.onLocation(function(location) {
    console.log('[location] -', location);
  });

  bgGeo.onMotionChange(function(event) {
    console.log('[motionchange] -', event.isMoving, event.location);
  });

  bgGeo.onHttp(function(response) {
    console.log('[http] - ', response.success, response.status, response.responseText);
  });

  bgGeo.onProviderChange(function(event) {
    console.log('[providerchange] -', event.status, event.enabled, event.gps, event.network);
  });

  // 2. Execute #ready method:
  bgGeo.ready({
    reset: true,
    debug: true,
    logLevel: bgGeo.LOG_LEVEL_VERBOSE,
    desiredAccuracy: bgGeo.DESIRED_ACCURACY_HIGH,
    distanceFilter: 10,
    url: '192.168.1.106:9000/locations',
    params: BackgroundGeolocation.transistorTrackerParams(window.device),
    autoSync: true,
    stopOnTerminate: false,
    startOnBoot: true
  }, function(state) {    // <-- Current state provided to #configure callback
    // 3.  Start tracking
    console.log('BackgroundGeolocation is configured and ready to use');
    if (!state.enabled) {
      bgGeo.start().then(function() {
        console.log('- BackgroundGeolocation tracking started');
      });
    }
  });

  // NOTE:  Do NOT execute any API methods which will access location-services
  // until the callback to #ready executes!
  //
  // For example, DO NOT do this here:
  //
  // bgGeo.getCurrentPosition();   // <-- NO!
  // bgGeo.start();                // <-- NO!
    }

**Comment by marking11** [comment]
Hello ,
https://github.com/transistorsoft/cordova-background-geolocation-SampleApp/blob/master/examples/cordova-basic/www/js/index.js
 this example it s not wokring neither on your server we don t have location on DATA neither on local the database still empty.

Thanks,

**Comment by christocracy** [comment]
There's nothing wrong with the server.  That "cordova-basic" example hasn't been touched since 2017.

**Comment by marking11** [comment]
check this user please  http://tracker.transistorsoft.com/YYY11  check the DATA is empty

**Comment by christocracy** [comment]
Yes, because the EXAMPLE CODE IS WRONG.  I haven't TOUCHED it since 2017.

Don't use that code.

**Comment by christocracy** [comment]
For pure Cordova usage:

1.  Use [this code](https://github.com/transistorsoft/cordova-background-geolocation-lt#cordova--ionic-1)

2.  See docs [BackgroundGeolocation.transistorTrackerParams](https://transistorsoft.github.io/cordova-background-geolocation-lt/classes/_cordova_background_geolocation_lt_.backgroundgeolocation.html#transistortrackerparams)

**Comment by christocracy** [comment]
There:  [updated cordova-basic for 2019](https://github.com/transistorsoft/cordova-background-geolocation-SampleApp/commit/3b80737726250ccc13ad7650ee9a256fe7d56ee9)

**Comment by marking11** [comment]
Thanks for the update.
cordova.js:309 Uncaught TypeError: bgGeo.onMotionchange is not a function
    at Object.configureBackgroundGeolocation (index.js:69)
    at Object.<anonymous> (index.js:40)
    at index.js:236
    at Object.callbackFromNative (cordova.js:288)
    at <anonymous>:1:9

**Comment by christocracy** [comment]
Install latest version of background-geolocation.  You're either using too old a version or the plugin isn't installed.

**Comment by marking11** [comment]
Thanks for your response, i have the latest version of the plugin.
cordova-background-geolocation-lt 3.0.5 "BackgroundGeolocation"
cordova-plugin-background-fetch 5.4.1 "CDVBackgroundFetch"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-dialogs 2.0.2-dev "Notification"
cordova-plugin-whitelist 1.3.3 "Whitelist"

**Comment by marking11** [comment]
bgGeo.on('motionchange', function(isMoving, location) it means that the plugin is installed ,
cordova-background-geolocation-lt 3.0.5 "BackgroundGeolocation" means that i have the latest version.

**Comment by christocracy** [comment]
Typo:  `onMotionchange` -> `onMotionChange`.

Do you ever inspect your app in the Javascript Console with `chrome://inspect/#devices?

![](https://dl.dropbox.com/s/ta6mtchzxxpsgsv/Screenshot%202019-05-16%2009.28.15.png?dl=1)

**Comment by christocracy** [comment]
If you did, you might have quickly discovered the typo:
![](https://dl.dropbox.com/s/umz920y0c4koh89/Screenshot%202019-05-16%2009.29.25.png?dl=1)

**Comment by marking11** [comment]
Yes now it works and we can save record on the database 
<img width="1258" alt="Capture d’écran 2019-05-16 à 1 32 46 PM" src="https://user-images.githubusercontent.com/50495013/57857703-327d5e00-77df-11e9-9fad-d1af4ed3ad91.png">

**Comment by christocracy** [comment]
And this question?

>Do you ever inspect your app in the Javascript Console with chrome://inspect/#devices?

**Comment by marking11** [comment]
Still the same error 
<img width="1431" alt="Capture d’écran 2019-05-16 à 1 38 37 PM" src="https://user-images.githubusercontent.com/50495013/57858096-f1397e00-77df-11e9-9a6d-ceba55c538d2.png">

**Comment by christocracy** [comment]
Do you not understand what this *means*?

>Typo: `onMotionchange` -> `onMotionChange`.

Yes, THERE IS NO FUNCTION NAMED `onMotionchange`!  The name is `onMotionChange`.

>bg = window.BackgroundGeolocation

Look at the methods available to you.

**Comment by christocracy** [comment]
And yes, it was *me* who made that mistake but I'm not impressed with your inability to load the Javascript console and figure out the problem for yourself.

**Comment by christocracy** [comment]
The [sample code in the plugin README](https://github.com/transistorsoft/cordova-background-geolocation-lt#cordova--ionic-1) **is correct**.

**Comment by marking11** [comment]
I updated the comment, i was in the wrong window of the issue.
<img width="1437" alt="Capture d’écran 2019-05-16 à 1 54 05 PM" src="https://user-images.githubusercontent.com/50495013/57859402-60b06d00-77e2-11e9-9fa6-e2fb4a3ade0c.png">

**Comment by marking11** [comment]
hello , i installed the web app on a remote server, run the server , when debugging i get this errors

<img width="1365" alt="Capture d’écran 2019-05-17 à 4 25 06 PM" src="https://user-images.githubusercontent.com/50495013/57942226-7300d880-78c0-11e9-8d9a-a1e1c5c9a192.png">
<img width="1364" alt="Capture d’écran 2019-05-17 à 4 23 13 PM" src="https://user-images.githubusercontent.com/50495013/57942227-7300d880-78c0-11e9-9bad-d2798a13d79a.png">

**Comment by christocracy** [comment]
I have no idea.  If you're installing this on a remote-server, you're on your own.  I don't provide support for that.

**Comment by marking11** [comment]
i fixed the bug by uninstall and install the sqlite3 manually, now i get this error 
<img width="1374" alt="Capture d’écran 2019-05-17 à 5 03 13 PM" src="https://user-images.githubusercontent.com/50495013/57944185-ae51d600-78c5-11e9-8a4a-ff22fe279d93.png">
