### ISSUE TITLE
Nothing happen in MAP and DATA tab

### ISSUE THREAD

**Issue by kiddkevin00** [transistorsoft/background-geolocation-console#62]
Hi Chris,

I follow your README setup. The server is receiving POST request from my simulator using location simulate City Bike Ride. But the MAP and DATA tab has nothing there. How to show get the data showing?

![Screen Shot 2019-05-22 at 10 02 46 AM](https://user-images.githubusercontent.com/7229339/58180881-cd12ec80-7c78-11e9-8020-2e530cb99a1b.png)
![Screen Shot 2019-05-22 at 10 02 37 AM](https://user-images.githubusercontent.com/7229339/58180882-cd12ec80-7c78-11e9-8546-65c2038609e9.png)

**Comment by christocracy** [comment]
When you see *Device: UNKNOWN*, you failed to provide the required Device `#params` to the plugin config.

**Comment by christocracy** [comment]
- If you are using Cordova or React Native, see docs `BackgroundGeolocation.transistorTrackerParams`.
- if you are using Flutter, see docs `Config.deviceParams`

**Comment by kiddkevin00** [comment]
Is that required?

Also, I keep getting this when simulating location in simulator:

![Screen Shot 2019-05-22 at 10 19 53 AM](https://user-images.githubusercontent.com/7229339/58182253-46134380-7c7b-11e9-9fee-8c0b69bba085.png)

Any clue how to fix this "[location] ERROR - 0" from console.error

**Comment by christocracy** [comment]
>Is that required?

It is absolutely required.  How is the server [supposed to differentiate between devices](Is that required?) since it has no "login system" or authentication tokens. 


location error: 0 means the native Location API failed to provide a location to the plugin.

If the native Location API were a tap of water, error-code `0` means you turned the tap and no water flowed out.

**Comment by kiddkevin00** [comment]
Got it. I got the water running by waiting for the tap a bit longer. Last question: how do I get the real-time location update on the website like the one in your demo video? Right now, I need to refresh the page to get the latest location update.

![Screen Shot 2019-05-22 at 10 44 17 AM](https://user-images.githubusercontent.com/7229339/58184265-c5eedd00-7c7e-11e9-883d-de2213dd85ad.png)

**Comment by christocracy** [comment]
I don't think `background-geolocation-console` *has* a feature to auto-update.
