### ISSUE TITLE
General question about `getOdometer()`

### ISSUE THREAD

**Issue by kiddkevin00** [transistorsoft/background-geolocation-console#64]
What the return value of `getOdometer()` or location.odometer from `on('Location', (location) => {})`? We need a very accurate traveled distance. Do we need to add the value of the distance between previous LatLng and new LatLng using Haversine formula to calculate additionally? In other words, the traveled distance will be `location.odometer` from location listener plus `haversine(previousLatLng, newLatLng)`. Will that give me the accurate traveled distance?

**Comment by christocracy** [comment]
Odometer is an accumulated distance in meters the device has travelled.  You don’t need to do anything else.
