### ISSUE TITLE
Delete Device data by time period.

### ISSUE THREAD

**Issue by christocracy** [transistorsoft/background-geolocation-console#66]
Currently, the delete action in *Locations* panel will delete **all** that device data.

On the confirmation modal dialog, I'd like a checkbox:

- [x] Delete selected dates only
- [x] Do not reload Companies on each device change (when that does not needed)
- [x] Add persist support for checkboxes

**Comment by christocracy** [comment]
Sometimes I use I simulate location and I want to destroy only a selected block of location data (start -> end date) and not the whole device:

![](https://dl.dropbox.com/s/tfmgklplggne7r0/Screenshot%202019-09-11%2019.52.26.png?dl=1)

**Comment by Sigura** [comment]
I think it can be closed. Or I'm missing something?
