### ISSUE TITLE
Homepage loading with error

### ISSUE THREAD

**Issue by svnindia** [transistorsoft/background-geolocation-console#7]
Warning: "menuItems" property of "SelectField" has been deprecated.
to promote composability.

Warning: "displayMember" property of "DropDownMenu" has been deprecated.
Instead, use composability.

Warning: "menuItems" property of "DropDownMenu" has been deprecated.
Instead, use composability.

Warning: "valueMember" property of "DropDownMenu" has been deprecated.
Instead, use composability.

**Comment by christocracy** [comment]
Do you know how to fix it?

**Comment by svnindia** [comment]
ok let me try to fix and give the patch by this weekend

**Comment by svnindia** [comment]
Fixed the issue in my forked branch, please accept my pull request

**Comment by christocracy** [comment]
Thanks, I'll try it out
