### ISSUE TITLE
psql function to reformat Device.device_model and populate Device.framework

### ISSUE THREAD

**Issue by christocracy** [transistorsoft/background-geolocation-console#93]
We need a psql script to iterate `devices` table and populate the `framework` column where `null`

![](https://dl.dropbox.com/s/2lpnxmn3dfb1k27/Screenshot%202019-12-03%2008.23.40.png?dl=1)

An old style `device_model` takes the form:

| device_model        | framework     |
|------------------|--------------|
| Moto G (5) Plus (ReactNative)    | `null`   |

Where `Framework` takes the form:
- ReactNative
- Flutter
- Cordova

We need to find that text `FrameworkName`, *remove it* (including brackets) from `device_model` and use it to populate `framework`.
- In the end, the two columns will look like this:

| device_model        | framework     |
|------------------|--------------|
| Moto G (5) Plus    | react-native   |

- I want the framework name reformatted too, such that:
  - `ReactNative` -> `react-native`
  - `Cordova` -> `cordova`
  - `Flutter` -> `flutter`

**Comment by Sigura** [comment]
```
update public.devices
  device_model = REGEXP_REPLACE(device_model, '^([^(]*).*$', '\1') as device_model,
  framework = (
    CASE REGEXP_REPLACE(device_model, '^[^(]*\(([^)]*)\)$', '\1')
        WHEN 'ReactNative' THEN 'react-native'
            WHEN 'Cordova' THEN 'cordova'
        WHEN 'Flutter' THEN 'flutter'
            ELSE null
        END
  )  
where framework is null;
```

**Comment by christocracy** [comment]
Sample data after execute:
![](https://dl.dropboxusercontent.com/s/9htsbrd2gwycnyw/Screenshot%202019-12-03%2019.31.46.png?dl=1)

**Comment by Sigura** [comment]
Looks like all is fine and we can close this issue?
