### ISSUE TITLE
 Wrong distance is calculated issue.

### ISSUE THREAD

**Issue by Jitendranagar** [transistorsoft/background-geolocation-console#97]
The  odometer  value  is  1058919  and time  is  "2019-12-09T06:50:45" for id 1611552  and next  odometer  value is  1061805 and  time 2019-12-09T06:50:55 for id 1611553. The time difference  is  5 second and difference in odometer  value is (1061805-1058919)=2886  which is very  big and therefor wrong distance is calculated.  how to fix this issue? 

This issue found multiple times. 
 PFA.
![Tracking_issue](https://user-images.githubusercontent.com/6169697/71002684-cf9dcd80-2105-11ea-8ff8-9d88ec8bc01b.png)

**Comment by christocracy** [comment]
Incorrect repo.
