### ISSUE TITLE
We will not run server. Unhandled error.

### ISSUE THREAD

**Issue by Jitendranagar** [transistorsoft/background-geolocation-console#98]
Hi, Chris,

Have you implement web-application in php language? any document link  for implement in php language. 
I have try to nodejs  web application.
My environment:
 Windows 10
node:v12.14.0
npm: 6.13.4

we are implement  simple Node-based web-application with our app.  when run this command for Developer mode then error occur.

$ npm run dev

> background-geolocation-console@3.0.1 dev C:\xampp\htdocs\project\background-geolocation-console
> better-npm-run dev

'better-npm-run' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! background-geolocation-console@3.0.1 dev: `better-npm-run dev`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the background-geolocation-console@3.0.1 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Admin\AppData\Roaming\npm-cache\_logs\2019-12-19T13_08_50_276Z-debug.log

**Comment by christocracy** [comment]
> Have you implement web-application in php 

I haven’t touched php since 2006.  Probably never will.

> 'better-npm-run' is not recognized as an internal or external command,

Did you run `npm install`?

**Comment by demency** [comment]
Hi @Jitendranagar, i have a laravel backend and quasarjs application compatible with this plugin. Send me a email iantorres@outlook.com 👍

**Comment by christocracy** [comment]
Server language / framework is irrelevant.  The plugin posts http requests, that’s it.

**Comment by dbsali** [comment]
Hi @christocracy, the app crashes when posting data to https any idea how to deal with this ?

**Comment by christocracy** [comment]
@dbsali your question has nothing to do with issue.
